# Generated by Django 5.2.13 on 2026-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Estudiante"),
                    ("teacher", "Docente"),
                    ("admin", "Administrador"),
                ],
                db_index=True,
                default="student",
                max_length=16,
            ),
        ),
    ]
