# Generated by Django 5.2.13 on 2026-05-15 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0001_initial"),
        ("accounts", "0002_student_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academia.program",
                verbose_name="Carrera / programa",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_semester",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Semestre académico"
            ),
        ),
    ]
