# Generated by Django 5.2.13 on 2026-05-15 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Nombre"),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="Inicio"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Período actual"
                    ),
                ),
            ],
            options={
                "verbose_name": "Período académico",
                "verbose_name_plural": "Períodos académicos",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(blank=True, max_length=32, verbose_name="Código"),
                ),
                ("slug", models.SlugField(max_length=220, unique=True)),
            ],
            options={
                "verbose_name": "Carrera / programa",
                "verbose_name_plural": "Carreras / programas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Offering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del curso"),
                ),
                ("code", models.CharField(max_length=64, verbose_name="Código")),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Semestre"
                    ),
                ),
                (
                    "group",
                    models.CharField(default="A", max_length=16, verbose_name="Grupo"),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Créditos"
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="academia.academicperiod",
                        verbose_name="Período",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_offerings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Docente responsable",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="academia.program",
                        verbose_name="Carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso académico (oferta)",
                "verbose_name_plural": "Cursos académicos (ofertas)",
                "ordering": ["-period__name", "program__name", "code"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("withdrawn", "Baja")],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inscripción"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academia.offering",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "ordering": ["-enrolled_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("offering", "student"),
                        name="academia_enrollment_unique_offering_student",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="offering",
            constraint=models.UniqueConstraint(
                fields=("program", "code", "period", "group"),
                name="academia_offering_unique_program_code_period_group",
            ),
        ),
    ]
