# Generated by Django 5.2.13 on 2026-05-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offering",
            options={
                "ordering": ["-period__name", "program__name", "code"],
                "verbose_name": "Curso ofertado",
                "verbose_name_plural": "Cursos ofertados",
            },
        ),
    ]
