# Generated by Django 5.2.13 on 2026-05-17 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academia", "0002_alter_offering_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveSmallIntegerField(verbose_name="Número de semana"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tema")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="Inicio"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Bloqueada"),
                            ("available", "Disponible"),
                            ("in_progress", "En curso"),
                            ("completed", "Completada"),
                        ],
                        default="available",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_weeks",
                        to="academia.offering",
                        verbose_name="Curso ofertado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semana académica",
                "verbose_name_plural": "Semanas académicas",
                "ordering": ["offering", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instrucciones"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("task", "Tarea"),
                            ("workshop", "Taller"),
                            ("forum", "Foro"),
                            ("quiz", "Cuestionario"),
                            ("exam", "Examen"),
                            ("practice", "Práctica"),
                            ("delivery", "Entrega"),
                        ],
                        default="task",
                        max_length=16,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha límite"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("closed", "Cerrada"),
                        ],
                        default="published",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "allows_draft",
                    models.BooleanField(default=True, verbose_name="Permite borrador"),
                ),
                (
                    "allow_late",
                    models.BooleanField(
                        default=False, verbose_name="Permite entrega tardía"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=4,
                        verbose_name="Puntaje máximo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="classroom.academicweek",
                        verbose_name="Semana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["week", "due_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "Alta")],
                        default="normal",
                        max_length=8,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Publicado"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="academia.offering",
                        verbose_name="Curso ofertado",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="classroom.academicweek",
                        verbose_name="Semana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("closed", "Cerrado")],
                        default="open",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Publicado"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forums_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums",
                        to="classroom.academicweek",
                        verbose_name="Semana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foro",
                "verbose_name_plural": "Foros",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Documento"),
                            ("video", "Video"),
                            ("image", "Imagen"),
                            ("link", "Enlace"),
                            ("presentation", "Presentación"),
                            ("other", "Otro"),
                        ],
                        default="document",
                        max_length=16,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="classroom/materials/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Enlace externo"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Obligatorio"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Publicado"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publicado por",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="classroom.academicweek",
                        verbose_name="Semana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material de estudio",
                "verbose_name_plural": "Materiales de estudio",
                "ordering": ["week", "title"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="classroom/submissions/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentario")),
                (
                    "is_draft",
                    models.BooleanField(default=True, verbose_name="Es borrador"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Entregada"),
                            ("late", "Tardía"),
                            ("graded", "Calificada"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classroom.activity",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Nota"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Retroalimentación"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de calificación"
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calificado por",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="classroom.submission",
                        verbose_name="Entrega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
            },
        ),
        migrations.AddConstraint(
            model_name="academicweek",
            constraint=models.UniqueConstraint(
                fields=("offering", "week_number"),
                name="classroom_week_unique_offering_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("activity", "student"),
                name="classroom_submission_unique_activity_student",
            ),
        ),
    ]
